#!/bin/bash

function close() {
	eww -c "$HOME/.config/eww/iceberg/menu" close sys-menu time-menu
	$HOME/.scripts/dashboard close
}

function lock() {
	#close
	#betterlockscreen -l dim
  ~/.config/hypr/scripts/lock
}

function llogout() {
	close
	bspc quit
}

function rrestart() {
	close
	reboot
}

function sshutdown() {
	close
	shutdown now
}

function hhibernate() {
  ~/.config/hypr/scripts/hibernate
}

case "$1" in
	lock) lock;;
	logout) llogout;;
	reboot) rrestart;;
	shutdown) sshutdown;;
  hibernate) hhibernate;;
	*) echo "unrecognized command" && exit 1;;
esac

