#!/bin/bash
if [ -f ~/.cache/power/alarm.lock ] 
then
  rm ~/.cache/power/suspend.lock
  ~/wakeup.sh 
  #~/newyear.sh
else
  ~/.config/hypr/scripts/lock # comment this line out if you're using disk encryption 
  rm ~/.cache/power/suspend.lock
  #systemd-inhibit --what=handle-lid-switch sleep 3s &
  sleep 2
  systemctl hibernate 
fi
