#!/bin/bash

function down(){
  for i in `seq 5`; do brightnessctl s 1%- -q && sleep 0.02; done
}
function up(){
  for i in `seq 5`; do brightnessctl s +1% -q && sleep 0.02; done
}

case "$1" in
  "down") down;;
  "up") up;;
  *) echo "unknown command";;
esac
