#!/bin/bash
set -ex

CACHE_DIR="/home/waverider/.cache/eww"

trap "killall paplay; killall breaktimer; exit" TERM

# -- DISCIPLINE --
#
# checks if the focused window is on-topic to the current focus activity

# activity whitelist
math_whitelist="Brave qalc BASS kitten Cavasik cava Open math Picture LibreWolf krita mpv"

# window class whitelist
math_class_whitelist="nemo bassmod org.gnome.Loupe cmus zenity pavucontrol blueman-manager Brave org.kde.gwenview pinta vlc BreakTimer qalc LibreWolf krita"

hits=1

function disabled() {
  if
    [ -f "$CACHE_DIR/math.lock" ] &&
    [ -f "$CACHE_DIR/web.lock" ] &&
    [ -f "$CACHE_DIR/cts.lock" ] &&
    true
    then
    exit
  fi
} 

#/opt/appimages/BreakTimer.AppImage & disown 

while sleep 0.25; do
  disabled

  prevhit=$hits

  prevwindow=$window

  activewindow=$(hyprctl --batch activewindow)
  window=$(echo "$activewindow" | grep "initialTitle")

  if [ "$prevwindow" != "$activewindow" ]; then

    windowclass=$(echo "$activewindow" | grep "class")

    if [ ! -f "$CACHE_DIR/math.lock" ]; then
      if [ "$window" != "" ]; then
        for word in $math_whitelist; do
          if [[ "$window" == *"$word"* ]]; then
            hits=1
            break
          else
            hits=0
          fi
        done
        if [ $hits != 1 ]; then
          for word2 in $math_class_whitelist; do
            if [[ "$windowclass" == *"$word2"* ]]; then
              hits=1
              break
            else
              hits=0
            fi
          done
        fi
      else
        hits=1
      fi
    fi

    # web whitelist
    web_whitelist="Brave qalc BASS kitten Cavasik cava Open LibreWolf Settings Central Piedmont kitty Translate Wikipedia"
    web_class_whitelist="nemo bassmod org.gnome.Loupe cmus zenity pavucontrol blueman-manager Brave pinta BreakTimer qalc LibreWolf"

    if [ ! -f "$CACHE_DIR/web.lock" ]; then
      if [ "$window" != "" ]; then
        for word in ${web_whitelist}; do
          if [[ "$window" == *"$word"* ]]; then
            hits=1
            break
          else
            hits=0
          fi
        done
        if [ $hits != 1 ]; then
          for word2 in ${web_class_whitelist}; do
            if [[ "$windowclass" == *"$word2"* ]]; then
              hits=1
              break
            else
              hits=0
            fi
          done
        fi
      else
        hits=1
      fi
    fi
    # cts whitelist
    cts_whitelist="Brave qalc BASS kitten Cavasik cava Open LibreWolf Settings Central Piedmont Translate Wikipedia"
    cts_class_whitelist="nemo bassmod org.gnome.Loupe cmus zenity pavucontrol blueman-manager Brave pinta BreakTimer qalc LibreWolf"

    if [ ! -f "$CACHE_DIR/cts.lock" ]; then
      if [ "$window" != "" ]; then
        for word in ${cts_whitelist}; do
          if [[ "$window" == *"$word"* ]]; then
            hits=1
            break
          else
            hits=0
          fi
        done
        if [ $hits != 1 ]; then
          for word2 in ${cts_class_whitelist}; do
            if [[ "$windowclass" == *"$word2"* ]]; then
              hits=1
              break
            else
              hits=0
            fi
          done
        fi
      else
        hits=1
      fi
    fi
    if [ $hits == 0 ] && [ $prevhit == 0 ]; then
      if ! pgrep -x "paplay" > /dev/null; then
        paplay ~/.config/hypr/sounds/sponge.flac &
      fi
      hits=1
    elif [ $hits == 1 ]; then
      if pgrep -x "paplay" > /dev/null; then
        killall paplay
      fi
      hits=0
    fi
  fi
done
