#!/bin/bash
#set -ex
MAX=$(brightnessctl g)
brightnessctl s 0
CURRENT=0
INDEX=MAX/100
sleep 1.5
while [ $CURRENT -le $MAX ]; do
  brightnessctl s $CURRENT -q;
  CURRENT=$(($CURRENT + INDEX)) ;
done
sleep 1

