#!/bin/bash
#set -ex

CACHE_DIR="/home/waverider/.cache/eww"

trap "killall paplay; exit" TERM

# -- DISCIPLINE --
#
# checks if the focused window is on-topic to the current focus activity

# activity whitelist
chem_whitelist="Brave qalc Kalzium BASS kitten Cavasik cava Open chem math"
math_whitelist="Brave qalc BASS kitten Cavasik cava Open math"

chem_class_whitelist="nemo bassmod org.gnome.Loupe cmus zenity pavucontrol blueman-manager"
math_class_whitelist="nemo bassmod org.gnome.Loupe cmus zenity pavucontrol blueman-manager"

hits=1

while sleep 0.25; do

  if [ -f "$CACHE_DIR/chem.lock" ] && [ -f "$CACHE_DIR/math.lock" ]; then
    exit
  fi

  prevhit=$hits

  prevwindow=$window

  activewindow=$(hyprctl --batch activewindow)
  window=$(echo "$activewindow" | grep "initialTitle")

  if [ "$prevwindow" != "$activewindow" ]; then

    windowclass=$(echo "$activewindow" | grep "class")

    if [ ! -f "$CACHE_DIR/chem.lock" ]; then
      if [ "$window" != "" ]; then
        for word in $chem_whitelist; do
          if [[ "$window" == *"$word"* ]]; then
            hits=1
            break
          else
            hits=0
          fi
        done
        if [ $hits != 1 ]; then
          for word2 in $chem_class_whitelist; do
            if [[ "$windowclass" == *"$word2"* ]]; then
              hits=1
              break
            else
              hits=0
            fi
          done
        fi
      else
        hits=1
      fi
    fi

    if [ ! -f "$CACHE_DIR/math.lock" ]; then
      if [ "$window" != "" ]; then
        for word in $math_whitelist; do
          if [[ "$window" == *"$word"* ]]; then
            hits=1
            break
          else
            hits=0
          fi
        done
        if [ $hits != 1 ]; then
          for word2 in $math_class_whitelist; do
            if [[ "$windowclass" == *"$word2"* ]]; then
              hits=1
              break
            else
              hits=0
            fi
          done
        fi
      else
        hits=1
      fi
    fi

    if [ $hits == 0 ] && [ $prevhit == 0 ]; then
      if ! pgrep -x "paplay" > /dev/null; then
        paplay ~/.config/hypr/sounds/sponge.flac &
      fi
      hits=1
    elif [ $hits == 1 ]; then
      if pgrep -x "paplay" > /dev/null; then
        killall paplay
      fi
      hits=0
    fi
  fi
done
