#!/bin/bash
#set -ex
MAX=$(brightnessctl g)
brightnessctl s 0
~/.config/hypr/scripts/lock_boot
CURRENT=0
sleep 4
while [ $CURRENT -le $MAX ]; do
  brightnessctl s $CURRENT -q;
  CURRENT=$(($CURRENT + 100)) ;
done
sleep 1
