#!/bin/sh
date=$(date +%Y%m%d-%H%M%S)
date+="$(hostname)"
if [ ! -f ~/.cache/eww/chem.lock ]; then
  FILE=$HOME/Pictures/Screenshots/chem/"$date".png
elif [ ! -f ~/.cache/eww/math.lock ]; then
  FILE=$HOME/Pictures/Screenshots/math/"$date".png
elif [ ! -f ~/.cache/eww/gov.lock ]; then
  FILE=$HOME/Pictures/Screenshots/gov/${date}.png
elif [ ! -f ~/.cache/eww/codehs.lock ]; then
  FILE=$HOME/Pictures/Screenshots/codehs/${date}.png
else
  FILE=$HOME/Pictures/Screenshots/${date}.png
fi
#grim -g "$(slurp)" $FILE && wl-copy < $FILE
grimblast --freeze copysave area $FILE
