#!/bin/sh
# NOTE: ONLY SUPPORTS TEXT

set -ex
#set -o pipefail
WINDOW_ID=$( hyprctl activewindow | grep Window | awk '{print $2}' )
TEXT=$( cliphist list | wofi --dmenu | cliphist decode )
#wl-copy $TEXT 
#sleep 1
#hyprctl dispatch focuswindow $WINDOW_ID 
wtype "${TEXT}"
#wtype -M ctrl -M shift -P v -m shift -m ctrl
#| wl-paste | wl-copy -c
