#!/bin/sh
date=$(date +%Y%m%d-%H%M%S)
date+="$(hostname)"
if [ ! -f ~/.cache/eww/chem.lock ]; then
  FILE=$HOME/Pictures/Screenshots/chem/"$date".png
elif [ ! -f ~/.cache/eww/math.lock ]; then
  FILE=$HOME/Pictures/Screenshots/math/${date}.png
elif [ ! -f ~/.cache/eww/web.lock ]; then
  FILE=$HOME/Pictures/Screenshots/web/${date}.png
elif [ ! -f ~/.cache/eww/cts.lock ]; then
  FILE=$HOME/Pictures/Screenshots/cts/${date}.png
else
  FILE=$HOME/Pictures/Screenshots/${date}.png
fi
grim $FILE && wl-copy < $FILE
#grimblast --freeze copysave screen $FILE
