#!/bin/bash
#set -ex
MAX=$(brightnessctl g)
brightnessctl s 0
~/.config/hypr/scripts/lock_boot
CURRENT=0
sleep 1.5
while [ $CURRENT -le $MAX ]; do
  brightnessctl s $CURRENT ;
  CURRENT=$(($CURRENT + 200)) ;
done
sleep 1

swww init
eww -c ~/.config/eww/bg open clock
eww -c ~/.config/eww/bg open bot
