#!/bin/sh

if [ "$#" -lt 1 ]; then
  echo "Usage: $0 <subject>"
  exit 1
fi

./discipline_remove.sh $1
./subjects_remove.sh $1
./sys_remove.sh $1
./imcp_remove.sh $1

echo "Done! Removed subject ${1}"
