#!/bin/bash

#set -ex

function refresh() {
  swww kill &
  killall swww-daemon
  killall eww
  sleep 0.5
  killall swww-daemon
  sleep 0.5
  swww init
  eww -c ~/.config/eww/bg open clock & disown;
  eww -c ~/.config/eww/bg open bot & disown;
}

export HDMIRES=1920x1080@60.00
#export HDMIRES=640x480@60.00
#export HDMIRES=1920x1200@60.00

if [ $1 = "mirror" ]; then
  hyprctl keyword monitor "eDP-1,preferred,auto,1"
  hyprctl keyword monitor "HDMI-A-1,$HDMIRES,0x0,1,mirror,eDP-1"
  refresh
elif [ $1 == "hdmi" ]; then
  hyprctl keyword monitor "HDMI-A-1,$HDMIRES,0x0,1"
  hyprctl keyword monitor "eDP-1,disable"
  refresh
elif [ $1 == "disp" ]; then
  hyprctl keyword monitor "HDMI-A-1,disable"
  #hyprctl keyword monitor "eDP-1,disable"
  hyprctl keyword monitor "eDP-1,preferred,auto,1"
  sleep 1
  systemctl --user restart xdg-desktop-portal-hyprland.service
  refresh
elif [ $1 == "both" ]; then
  hyprctl keyword monitor "HDMI-A-1,disable"
  hyprctl keyword monitor "eDP-1,preferred,auto,1"
  hyprctl keyword monitor "HDMI-A-1,$HDMIRES,0x0,1" 
  refresh
fi
